### PR TITLE
schema package: Build a python package with the schema

### PR DESCRIPTION
**Pull request by bjhargrave**
This will allow schema users to pip install the schema instead of using something like git submodules to place the schema files at some local path.

### CODE REVIEW

**Comment by bjhargrave** [comment]
@tiran Can you review the changes here to build a python package for the schema? The goal is to replace using git submodules (as we currently do) with a python dependency.

**Comment by tiran** [comment]
I'm happy to help. However I have very limited available until Jun 18th due to travel and other commitments.

**Comment by bjhargrave** [comment]
@russellb @nathan-weinberg Can either of you look at this PR? I would like to get it in (we can always sort out any issues with PyPI packaging later; the publish steps are "falsed" out now). Then other projects like the cli and taxonomy can move to use the package via a pip git+ url to this repo.

I have PRs in cli (https://github.com/instructlab/instructlab/pull/1285) and taxonomy (https://github.com/instructlab/taxonomy/pull/1169), to demonstrate accessing the schema via an installed package is working.

**Comment by bjhargrave** [comment]
I created a pending publisher for `instructlab-schema` as documented in https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/.

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
